---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: food-delivery
  labels:
    razee/watch-resource: detail
spec:
  selector:
    matchLabels:
      name: frontend
  replicas: 1
  template:
    metadata:
      labels:
        name: frontend
    spec:
      containers:
        - image: mcltn/example-food-frontend:1.0
          name: frontend
          imagePullPolicy: Always
          ports:
            - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: food-delivery
  labels:
    razee/watch-resource: detail
spec:
  ports:
    - port: 8090
      targetPort: 8090
  selector:
    name: frontend