apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: example-food
spec:
  port:
    targetPort: 8090
  to:
    kind: Service
    name: example-food
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: apiservice-path-creatorder
spec:
  path: "/createOrder"
  port:
    targetPort: 8080
  to:
    kind: Service
    name: apiservice
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: apiservice-path-status
spec:
  path: "/status"
  port:
    targetPort: 8080
  to:
    kind: Service
    name: apiservice
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: apiservice-path-restaurants
spec:
  path: "/restaurants"
  port:
    targetPort: 8080
  to:
    kind: Service
    name: apiservice
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: apiservice-path-user
spec:
  path: "/user"
  port:
    targetPort: 8080
  to:
    kind: Service
    name: apiservice
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: realtimedata-path-events
spec:
  path: "/events"
  port:
    targetPort: 8080
  to:
    kind: Service
    name: realtimedata
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: podconsumerdata-path-consumers
spec:
  path: "/consumers"
  port:
    targetPort: 8080
  to:
    kind: Service
    name: podconsumerdata
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: favorites-path
spec:
  path: "/favorites"
  port:
    targetPort: 8080
  to:
    kind: Service
    name: ksql-controller
---